name: Build Windows Portable

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Stickyn-Windows
        path: dist/Stickyn.exe
        
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/Stickyn.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}